import { RuleTester } from '@typescript-eslint/rule-tester'
import rule from './thin-route'

const ruleTester = new RuleTester({
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaFeatures: { jsx: true },
  },
})

ruleTester.run('thin-route', rule, {
  valid: [
    {
      code: `export default function Page() { return <div>Thin</div> }`,
      filename: '/project/src/screens/Home/page.tsx',
    },
  ],

  invalid: [
    {
      code: `
export default function FatPage() {
  const data = useData()
  // ... 20 lines of logic ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  // ...
  return <div>Too much logic</div>
}
      `,
      filename: '/project/src/screens/Dashboard/page.tsx',
      options: [{ maxLines: 10 }],
      errors: [{ messageId: 'thinRoute' }],
    },
  ],
})
